// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

import './AddFolderModal.css'
;

function AddFolderModal(props) {
  var handleClose = props.handleClose;
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("div", {
                            children: "Create Folder"
                          }),
                      JsxRuntime.jsx("input", {
                            value: props.folderValue,
                            onChange: props.onFolderChange
                          }),
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("button", {
                                    children: "Save",
                                    className: "save",
                                    onClick: props.handleFolderSave
                                  }),
                              JsxRuntime.jsx("button", {
                                    children: "Cancel",
                                    className: "cancel",
                                    onClick: handleClose
                                  })
                            ],
                            className: "footer"
                          }),
                      JsxRuntime.jsx("div", {
                            children: "Create File"
                          }),
                      JsxRuntime.jsx("input", {
                            value: props.fileValue,
                            onChange: props.onFileChange
                          }),
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("button", {
                                    children: "Save",
                                    className: "save",
                                    onClick: props.handleFileSave
                                  }),
                              JsxRuntime.jsx("button", {
                                    children: "Cancel",
                                    className: "cancel",
                                    onClick: handleClose
                                  })
                            ],
                            className: "footer"
                          })
                    ],
                    className: "inner-modal"
                  }),
              className: "outer-modal"
            });
}

var make = AddFolderModal;

export {
  make ,
}
/*  Not a pure module */
